<div class="title-line"></div>
<div class="title-contacts">Баннеры</div>
<div class="title-line"></div>

<div class="promotion-body-block_1">
    Мы заботимся о том, чтобы созданные нами сайты легко находились целевыми
    пользователями в интернете, поэтому мы комплексно подходим у их созданию
    , планируя методы продвижения уже на этапе проектирования
</div>

<div class="promotion-body-block_7">Цена:</div>

<div class="banners-price-table">
    <div class="banners-price-table_head">
        <div class="banners-price-table_item"></div>
        <div class="banners-price-table_item">88x31</div>
        <div class="banners-price-table_item">100x100</div>
        <div class="banners-price-table_item">120x60</div>
        <div class="banners-price-table_item">200x65</div>
        <div class="banners-price-table_item">468x60</div>
        <div class="banners-price-table_item">200x300</div>
    </div>
    <div class="banners-price-table_body_static">
        <div class="banners-price-table_item">Статический</div>
        <div class="banners-price-table_item">от 5000</div>
        <div class="banners-price-table_item">от 5000</div>
        <div class="banners-price-table_item">от 5000</div>
        <div class="banners-price-table_item">от 5000</div>
        <div class="banners-price-table_item">от 5000</div>
        <div class="banners-price-table_item">от 5000</div>
    </div>
    <div class="banners-price-table_body_animate">
        <div class="banners-price-table_item">Анимационный</div>
        <div class="banners-price-table_item">от 5000</div>
        <div class="banners-price-table_item">от 5000</div>
        <div class="banners-price-table_item">от 5000</div>
        <div class="banners-price-table_item">от 5000</div>
        <div class="banners-price-table_item">от 5000</div>
        <div class="banners-price-table_item">от 5000</div>
    </div>
</div>

<div class="promotion-body-carusel">
    <div class="promotion-body-carusel_first"></div>
    <div class="promotion-body-carusel_second"></div>
</div>

<div class="banners-body-table">
    <div class="promotion-body-table-cell">
        <div class="promotion-body-table-cell_number">1 </div>
        <div class="promotion-body-table-cell_text">Привлечение аудитории</div>
    </div>
    <div class="promotion-body-table-cell">
        <div class="promotion-body-table-cell_number">2 </div>
        <div class="promotion-body-table-cell_text">От 2 до 5 рабочих дней</div>
    </div>
    <div class="promotion-body-table-cell">
        <div class="promotion-body-table-cell_number">3 </div>
        <div class="promotion-body-table-cell_text">Привлечение аудитории</div>
    </div>
</div>

<div class="promotion-body-block_9">
    <a href="<?= $this->url('page', array('action' => 'checkout')) ?>">
        <div class="promotion-body-button_order">ОФОРМИТЬ ЗАКАЗ</div>
    </a>
    <div class="promotion-body-button_price">РАСЧИТАТЬ ЦЕНУ</div>
</div>

<style>
    .banners-body-table {
        overflow: hidden;
        margin: 20px auto 0;
        width: 600px;
    }
    .banners-price-table {
        text-align: center;
        font-size: 18px;
        padding-top: 20px;
    }
    .banners-price-table_head {
        font-weight: bold;
        border-bottom: 1px solid #dadada;
    }
    .banners-price-table_head, .banners-price-table_body_static,
    .banners-price-table_body_animate {
        padding-top: 10px;
        overflow: hidden;
    }
    
    .banners-price-table_item {
        float: left;
        width: 105px;
        height: 20px;
        line-height: 20px;
    }
    .banners-price-table_item:first-of-type {
        text-align: left;
        width: 170px;
        font-weight: bold;
    }
</style>