<div class="title-line"></div>
<div class="title-contacts">Узнаваемость бренда</div>
<div class="title-line"></div>

<div class="body-block_1  magrin_top_10">
    Увеличение узнаваемости бренда – первостепенная задача любогобизнеса.
</div>

<div class="body-block_1  magrin_top_10">
    Интернет-реклама или медийная реклама — это способ раскрутки бренда, то есть повышения его узнаваемости среди потенциальных покупателей.
</div>


<div class="body-block_3 magrin_top_20">
    Для чего это нужно?
</div>

<div class="body-block_6 body-color magrin_top_20">
    Потребителистараются покупать знакомый им товар (даже если «знакомство» состоялось пока только в Интернете),
    а значит, чем лучше раскрутить бренд, тем активнее идут продажи.
</div>

<div class="brend-images magrin_top_10">
    <div class="brend-images-part-1">
        <div class="brend-images-part-1_image"></div>
        <div class="brend-images-part-text">Раскрутка бренда<br/>(медийная реклама)</div>
        <div class="brend-arrow"></div>
    </div>
    <div class="brend-images-part-2">
        <div class="brend-images-part-2_image"></div>
        <div class="brend-images-part-text">Увеличение количества<br/>людей, знакомых с брендом</div>
        <div class="brend-arrow"></div>
    </div>
    <div class="brend-images-part-3">
        <div class="brend-images-part-3_image"></div>
        <div class="brend-images-part-text">РОСТ ПРОДАЖ</div>
    </div>
</div>

<div class="body-block_6 body-color magrin_top_20">
    Медийная реклама — это то, что люди видят, заходя на любой популярный сайт:
    рекламные баннеры. Большие и маленькие, статичные и анимированные – баннеры 
    могут быть любыми.  Они привлекают внимание и откладываются в памяти: это 
    самый верный и удачный способ повышения узнаваемости бренда, а следом и продаж.
</div>


<div class="body-block_4 magrin_top_20">В каких случаях наиболее эффективно заказывать<br/>медийную рекламу в Интернете?</div>

<ul class="body-ul_1 body-background body-color magrin_top_10">
    <li>Медийная реклама необходима молодым компаниям, чей бренд пока малоизвестен</li>
    <li>Она исключительно эффективна, когда надо повысить имидж бренда</li>
    <li>Баннерная реклама – это способ прямого воздействия на покупателя с целью побуждения его к покупке</li>
</ul>

<div class="body-block_1 magrin_top_20">Наша компания раскрутит Ваш бренд и сделает его известным<br/>широкой аудитории. <span class="body-color">Что это дает?</span></div>

<div class="body-block_6 body-background body-color magrin_top_20">
    Количество людей, готовых купить Ваш товар или услугу, увеличивается с каждым показом баннера
</div>

<div class="body-block_1 magrin_top_20">
    За короткий промежуток времени Вы охватываете максимально большое
    число потенциальных покупателей, многие из которых станут Вашими постоянными покупателями
</div>

<div class="body-block_4 magrin_top_20">Наши услуги по раскрутке бренда:</div>

<div class="body-table4 magrin_top_20">
    <div class="body-table4-cell">
        <div class="body-table4-cell_number">1 </div>
        <div class="body-table4-cell_text">разработка идеи баннерной рекламы</div>
    </div>
    <div class="body-table4-cell">
        <div class="body-table4-cell_number">2 </div>
        <div class="body-table4-cell_text">создание рекламных баннеров</div>
    </div>
    <div class="body-table4-cell">
        <div class="body-table4-cell_number">3 </div>
        <div class="body-table4-cell_text">размещение баннеров в Интернете</div>
    </div>
</div>

<div class="body-block_1 body-background magrin_top_20">
    Вы можете заказать раскрутку бренда «под ключ» или выбрать<br/>только те услуги, которые Вам нужны. 
</div>

<div class="body-block_3 magrin_top_20">
    Ищете, где заказать медийную рекламу в Минске? Мы предлагаем 
    Вам оптимальное сочетание цены и качества!
</div>

<div class="body-block_5 magrin_top_20">Цены:*</div>

<div class="body-table2">
    <div class="body-table2-cell">
        <div class="body-table2-cell_title">от 35 000 руб</div>
    </div>
    <div class="body-table2-cell">
        <div class="body-table2-cell_title">от 500 у.е</div>
    </div>
    <div class="body-table2-cell">
        <div class="body-table2-cell_title">от 750 у.е</div>
    </div>
</div>

<div class="body-block_6 magrin_top_10">
    * Стоимость продвижения формируется на основе целевых ключевых запросов, возраста сайта, уровня конкуренции, и необходимых позиций в поисковых системах.<br/>
    ** Для расчета стоимости, пожалуйста воспользуйтесь формой связи на сайте, позвоните нам или оставьте свой номер - наш менеджер свяжется с вами в ближайшее время.
</div>








<div class="body-block_7 magrin_top_20">
    <a href="<?= $this->url('page', array('action' => 'checkout')) ?>">
        <div class="body-button">Оформить заказ</div>
    </a>
</div>