<div class="title-icons">
    <a href="<?= $this->url('page', array('action' => 'promotion')) ?>">
        <div class="title-icon promotion_static"></div>
    </a>
    <div class="title-icon_main page_design"></div>
    <a href="<?= $this->url('page', array('action' => 'marketing')) ?>">
        <div class="title-icon marketing_static"></div>
    </a>
</div>
<div class="title_text">WEB Design</div>

<div class="design-body-block_1">WEB Дизайн от ABC Веб Медиа</div>

<div class="marketing-body-block_2">
    Что такое современный сайт?
</div>

<div class="design-body-block_3">Это единый инструмент который является лицом компании, офисом, отделом продаж и отделом<br/>
    по работе с клиентами. От того, на сколько Ваш сайт привлекателен, удобен в работе и<br/>
    популярен - зависит успех любого бизнес проекта.</div>

<div class="marketing-body-block_2">
    У Вас нет сайта?
</div>

<div class="design-body-block_5">
    МЫ ПОМОЖЕМ:
</div>

<div class="marketing-body-block_6">
    <ul>
        <li>разработать дизайн сайта привлекательный для Вашей целевой аудитории</li>
        <li>интернет магазин которым удобно пользоваться</li>
        <li>создать сайт который удобно и НЕ ДОРОГО поддерживать, обслуживать и развивать</li>
        <li>разработать сайт, оптимизированный под поисковые системы</li>
        <li>разработать мобильную версию сайта или приложение для Android, IOS (Apple), Windowsphone</li>
    </ul>
</div>

<div class="marketing-body-block_2">
    У вас уже есть сайт, но вы хотите чего-то нового?
</div>

<div class="design-body-block_5">
    НАША КОМПАНИЯ ПОМОЖЕТ:
</div>

<div class="marketing-body-block_6">
    <ul>
        <li>провести аудит и оптимизацию уже существующего сайта</li>
        <li>провести ребрендинг всего проекта или отдельных страниц</li>
        <li>внедрить системы управления сайтом и контроля заказов</li>
        <li>разработать дополнительные разделы сайта</li>
        <li>разработать международную версию существующего сайта</li>
    </ul>
</div>

<div class="promotion-body-block_8">
    Вебстудия компании Азбука Вебмедиа - команда профессиональныйх дизайнеров и программистов, с опытом работы более 10 лет. Мы создаем сайты ориентированные прежде всего на удобство пользователя. В работе используются самые современные подходы и технологии
</div>

<div class="promotion-body-block_7">Цены:*</div>

<div class="promotion-body-table2">
    <div class="promotion-body-table2-cell">
        <div class="promotion-body-table2-cell_title">от 500 у.е</div>
        <div class="promotion-body-table2-cell_text">Разработка<br/>сайта компании</div>
    </div>
    <div class="promotion-body-table2-cell">
        <div class="promotion-body-table2-cell_title">от 1000 у.е</div>
        <div class="promotion-body-table2-cell_text">Сайт с каталогом<br/>продукции либо интернет магазин</div>
    </div>
    <div class="promotion-body-table2-cell">
        <div class="promotion-body-table2-cell_title">от 3000 у.е.</div>
        <div class="promotion-body-table2-cell_text">Медийные или<br/>торговые порталы</div>
    </div>
</div>

<div class="design-body-block_1">Вы можете связаться с нами через форму на сайте или заказать звонок менеджера</div>

<div class="promotion-body-block_9">
    <a href="<?= $this->url('page', array('action' => 'checkout')) ?>">
        <div class="promotion-body-button_order">ОФОРМИТЬ ЗАКАЗ</div>
    </a>
</div>