<div class="title-icons">
    <div class="title-icon design_static"></div>
    <div class="title-icon_main page_marketing"></div>
    <div class="title-icon publicity_static"></div>
</div>
<div class="title_text">WEB Маркетинг</div>

<div class="promotion-body-block_1">
    <p>Маркетинговые исследования в интернете - незаменимый инструмент позволяющий<br/>
        быстро эффективно проводить сбор и анализ данных с различных целевых рынков</p>
</div>

<div class="marketing-body-block_2">
    Маркетинговые услуги от компании Азбука Вебмедиа:
</div>

<div class="marketing-body-block_3">

</div>

<div class="marketing-body-block_6">
    <ul>
        <li>Создание и продвижение тестовых продуктов в исследовательских целях</li>
        <li>Сбор и анализ рыночной информации о конкурентах</li>
        <li>Проведение опросов целевых групп пользователей</li>
        <li>Поддержка запуска новых продуктов и проектов</li>
        <li>Исследование покупательной способности</li>
        <li>Повышение узнаваемости бренда</li>
        <li>Исследование эффективности каналов рекламы в интернете для конкретных продуктов</li>
        <li>Маркетинговые исследования в социальных сетях</li>
        <li>Email маркетинг</li>
    </ul>
</div>

<div class="marketing-body-block_5">
    <div class="marketing-body-block_5-item_number">1</div>
    <div class="marketing-body-block_5-item_text">Специалисты по маркетингу компании Азбука Вебмедиа имеют научные степени в области
        экономики и маркетинга и обладают огромным опытом практической деятельности
        в бизнес сфере</div>
    <div class="marketing-body-block_5-item_number">2</div>
    <div class="marketing-body-block_5-item_text">В нашей компании Вы можете заказать как комплексное исследование всего рынка так и
        отдельные исследования по интересующим вас критериям</div>
    <div class="marketing-body-block_5-item_number">3</div>
    <div class="marketing-body-block_5-item_text">Мы поможем вам не только собрать и проанализировать информацию но и дадим
        рекомендации по организации рекламных и PR кампаний в глобальной сети</div>
</div>

<div class="marketing-body-block_7">Цены и сроки</div>

<div class="marketing-body-block_8">
    В зависимости от сложности поставленной задачи исследования занимают от 1 недели до года. Цены и условия
    обсуждаются с менеджерами отдела маркетинговых исследований. Вы можете заказать звонок прямо сейчас и
    с вами свяжутся в удобное для вас время
</div>

<div class="marketing-body-block_9">
    <div class="marketing-body-block_9-item"></div>
    <div class="marketing-body-block_9-item"></div>
    <div class="marketing-body-block_9-item"></div>
    <div class="marketing-body-block_9-item"></div>
</div>

<div class="promotion-body-block_9">
    <div class="promotion-body-button_order">ОФОРМИТЬ ЗАКАЗ</div>
    <div class="promotion-body-button_price">РАСЧИТАТЬ ЦЕНУ</div>
</div>