<div class="title">
    <div class="title-icon_main page_marketing"></div>
    <h1 class="title_text">WEB Маркетинг</h1>
    <p class="description-text">
        Маркетинговые исследования в интернете - незаменимый инструмент
        позволяющий быстро и эффективно проводить сбор и анализ данных с
        различных целевых рынков.
    </p>
</div>

<div class="separator-line">
    <div class="separator"></div>
</div>

<div class="marketing-body-image_part1">

</div>
<div class="marketing-body-image_part2">

</div>

<div class="body-block_9 magrin_top_10">
    Маркетинговые услуги от компании Азбука Медиа Групп:
</div>

    <ul class="body-ul_1 body-background2 magrin_top_20">
        <li>Создание и продвижение тестовых продуктов в исследовательских целях</li>
        <li>Сбор и анализ рыночной информации о конкурентах</li>
        <li>Проведение опросов целевых групп пользователей</li>
        <li>Поддержка запуска новых продуктов и проектов</li>
        <li>Исследование покупательной способности</li>
        <li>Повышение узнаваемости бренда</li>
        <li>Исследование эффективности каналов рекламы в интернете для конкретных продуктов</li>
        <li>Маркетинговые исследования в социальных сетях</li>
        <li>Email маркетинг</li>
    </ul>

<div class="body-table3 magrin_top_20">
    <div class="body-table3-item_number">1</div>
    <div class="body-table3-item_text">Специалисты по маркетингу компании Азбука Медиа Групп имеют научные степени в области
        экономики и маркетинга и обладают огромным опытом практической деятельности
        в бизнес сфере</div>
    <div class="body-table3-item_number">2</div>
    <div class="body-table3-item_text">В нашей компании Вы можете заказать как комплексное исследование всего рынка, так и
        отдельные исследования по интересующим вас критериям</div>
    <div class="body-table3-item_number">3</div>
    <div class="body-table3-item_text">Мы поможем вам не только собрать и проанализировать информацию, а так же дадим
        рекомендации по организации рекламных и PR кампаний в глобальной сети</div>
</div>

<div class="body-block_9 magrin_top_20">Цены и сроки</div>

<div class="body-block_6 body-background2 magrin_top_10">
    В зависимости от сложности поставленной задачи исследования занимают от 1 недели до года. Цены и условия
    обсуждаются с менеджерами отдела маркетинговых исследований. Вы можете заказать звонок прямо сейчас и
    с вами свяжутся в удобное для вас время.
</div>


<div class="marketing-body-slider">
    <?php echo $this->Marketing(); ?>
</div>

<div class="body-block_7 magrin_top_10">
    <a href="<?= $this->url('page', array('action' => 'checkout')) ?>">
        <div class="body-button">ОФОРМИТЬ ЗАКАЗ</div>
    </a>
</div>

<script>
    $(document).ready(function () {
        var slides = 4;
        var delay = (function () {
            var timer = 0;
            return function (callback, ms) {
                clearTimeout(timer);
                timer = setTimeout(callback, ms);
            };
        })();

        if ($(window).width() < 375) {
            slides = 2;
        } else if ($(window).width() < 510) {
            slides = 3;
        } else {
            slides = 4;
        }

        var slider = $('.marketing-body-slider').bxSlider({
            slideWidth: 105,
            minSlides: 1,
            maxSlides: slides,
            moveSlides: 1,
            slideMargin: 30,
            auto: true,
            pause: 2000,
            controls: false,
            pager: false,
        });

        $(window).resize(function () {
            delay(function () {
                if ($(window).width() < 375) {
                    slides = 2;
                } else if ($(window).width() < 510) {
                    slides = 3;
                } else {
                    slides = 4;
                }
                slider.destroySlider();
                slider.reloadSlider({
                    slideWidth: 105,
                    minSlides: 1,
                    maxSlides: slides,
                    moveSlides: 1,
                    slideMargin: 30,
                    randomStart: true,
                    auto: true,
                    pause: 2000,
                    controls: false,
                    pager: false,
                });
            }, 300);
        });
    });
</script>