<div class="title">
    <div class="title-icon_main page_publicity"></div>
    <h1 class="title_text">Реклама и PR</h1>
    <p class="description-text">
        Это - комплекс мер, направленый на увеличение посещения ресурса
        целевой аудиторий. Работа над повышением узнаваемости бренда: люди знают о Вас
        и ищут не разные компании, предлагающие подобные услуги, а именно Вас
    </p>
</div>

<div class="separator-line">
    <div class="separator"></div>
</div>


<div class="pr-body-image magrin_top_20">
</div>

<div class="body-block_2 magrin_top_20">
    <p>Мы предлагает вам следующие услуги по<br/>
        PR и рекламе в социальных сетях:</p>
</div>

<ul class="body-ul_1 padding_35 magrin_top_20">
    <li>Раскрутка групп в социальных сетях</li>
    <li>Увеличение узнаваемости вашего бренда</li>
    <li>Раскрутка в социальных сетях</li>
    <li>Оформление групп и страниц в социальных сетях</li>
    <li>Целевая реклама с продающими объявлениями, имеющими высокое соотношение<br/>Просмотр – заявка</li>
</ul>

<div class="body-table body-background2 magrin_top_20">
    <div class="body-table_title"></div>
    <div class="body-table-cell">
        <div class="body-table-cell_number">1 </div>
        <div class="body-table-cell_text">Более 300 успешно реализованых проектов</div>
    </div>
    <div class="body-table-cell">
        <div class="body-table-cell_number">2 </div>
        <div class="body-table-cell_text">Только  положительные  отзывы</div>
    </div>
    <div class="body-table-cell">
        <div class="body-table-cell_number">3 </div>
        <div class="body-table-cell_text">Не Используем публичные технологии,  мы разрабатываем свои</div>
    </div>
    <div class="body-table-cell">
        <div class="body-table-cell_number">4 </div>
        <div class="body-table-cell_text">Постоянное снижение  стоимости за переход нового клиента</div>
    </div>
</div>

<div class="body-block_4 magrin_top_20">Мы даем гарантию, что:<br/>Вы не пожелаете разрывать с нами деловые отношения</div>

<div class="body-block_5 magrin_top_20">от 200 уе в месяц*</div>

<div class="body-block_6 magrin_top_20">*Цена определяется, исходя из поставленных задач и сроков на реализацию<br/>
    **Пожалуйста воспользуйтесь формой онлайн связи на сайте, позвоните нам или оставьте свой номер - наш менеджер свяжется с вами в ближайшее время
</div>

<div class="marketing-body-slider">
    <?php echo $this->Marketing(); ?>
</div>

<div class="body-block_7 magrin_top_20">
    <a href="<?= $this->url('page', array('action' => 'checkout')) ?>">
        <div class="body-button">ОФОРМИТЬ ЗАКАЗ</div>
    </a>
</div>

<script>
    $(document).ready(function () {
        var slides = 4;
        var delay = (function () {
            var timer = 0;
            return function (callback, ms) {
                clearTimeout(timer);
                timer = setTimeout(callback, ms);
            };
        })();

        if ($(window).width() < 375) {
            slides = 2;
        } else if ($(window).width() < 510) {
            slides = 3;
        } else {
            slides = 4;
        }

        var slider = $('.marketing-body-slider').bxSlider({
            slideWidth: 105,
            minSlides: 1,
            maxSlides: slides,
            moveSlides: 1,
            slideMargin: 30,
            auto: true,
            pause: 2000,
            controls: false,
            pager: false,
        });

        $(window).resize(function () {
            delay(function () {
                if ($(window).width() < 375) {
                    slides = 2;
                } else if ($(window).width() < 510) {
                    slides = 3;
                } else {
                    slides = 4;
                }
                slider.destroySlider();
                slider.reloadSlider({
                    slideWidth: 105,
                    minSlides: 1,
                    maxSlides: slides,
                    moveSlides: 1,
                    slideMargin: 30,
                    randomStart: true,
                    auto: true,
                    pause: 2000,
                    controls: false,
                    pager: false,
                });
            }, 300);
        });
    });
</script>