<div class="title">
    <div class="title-icon_main page_promotion"></div>
    <h1 class="title_text">Продвижение</h1>
    <p class="description-text">
        Это - комплекс мер, направленный на улучшение индексации сайта
        поисковыми системами и увеличение посещаемости ресурса
    </p>
</div>

<div class="separator-line">
    <div class="separator"></div>
</div>

<div class="body-simple-text magrin_top_20">
    Азбука вебмедиа&trade; предлагает вам следущие услуги<br/>
    по раскрутке, продвижению и рекламе в интернете:
</div>

<div class="promotion-table magrin_top_20">
    <div class="promotion-table-cell">
        <div class="promotion-table-cell-icon lupa-img"></div>
        <div class="promotion-table-cell-text">
            <span class="bold">Вывод вашего сайта на вершину поиска:</span>
            обеспечит вашей компании постоянный поток потенциальных клиентов.
            Превосходство данного рекламного метода над другими заключается в
            том, что все просмотры вашего интернет сайта будут являться целевыми.
            Достижение вершины поисковой выдачи - это комплексная задача,
            реализуемая с учетом сотен различных факторов внутренней и внешней
            оптимизации.
        </div>
    </div>
    <div class="promotion-table-cell">
        <div class="promotion-table-cell-icon monitor-img"></div>
        <div class="promotion-table-cell-text">
           <span class="bold">Внутренняя оптимизация и улучшение юзабилити:</span>
           необходимы для улучшения индексации вашего сайта поисковыми машинами,
           а так же для улучшения конвертации посетителей вашего интернет сайта
           в клиентов вашей компании. Интернет сайт должен быть удобным для
           чтения и осознания как для человека, так и для машины.

        </div>
    </div>
    <div class="promotion-table-cell">
        <div class="promotion-table-cell-icon grafik-img"></div>
        <div class="promotion-table-cell-text">
            <span class="bold">Создание и управление компаниями яндекс.директ
            и google.adwords:</span> преимущество данного рекламного метода
            состоит в том, что вы получаете реальных целевых посетителей на ваш
            интернет сайт одновременно со стартом вашей рекламной компании. 
            С использованием данных рекламных компаний вам нет необходимости
            ждать пока ваш сайт будет многократно проиндексирован поисковыми
            машинами и оценен соответствующим местом на вершине поиска. 
        </div>
    </div>
    <div class="promotion-table-cell">
        <div class="promotion-table-cell-icon dollar-img"></div>
        <div class="promotion-table-cell-text">
            <span class="bold">Внедрение систем мониторинга эффективности рекламы:</span>
            возможность мониторинга эффективности рекламной компании необходима
            для планирования рекламного бюджеда, а также для оценки ее целесообразности.
        </div>
    </div>
</div>

<div class="separator-line">
    <div class="separator"></div>
</div>

<div class="body-block_3  magrin_top_20">Почему именнно мы?</div>

<ul class="body-ul_1 padding_70 magrin_top_20">
    <li>Наша компания более 10 лет занимается продвижением проектов в интернете</li>
    <li>У нас огромный опыт с целевыми рынками США, Европы и России</li>
    <li>Мы используем самые передовые технологии и всегда добиваемся результата</li>
    <li>С нами легко работать. Каждого клиента ведет персональный менеджер</li>
    <li>Мы заботимся о ваших бюджетах и всегда стараемся оптимизировать все процессы для уменьшения расходов</li>
</ul>

<div class="body-block_4 magrin_top_20">Мы даем гарантию, что:</div>

<ul class="body-ul_1 body-background2 magrin_top_10">
    <li>ваши сайты достигнут целевых показателей и надолго закрепяться на первых позициях</li>
    <li>оптимизированные нами страницы продуктов и сайты заметно повысят интерес со стороны посетителей</li>
    <li>сроки выполнения даже самых амбициозных задач не превысят 6 месяцев</li>
</ul>

<div class="body-block_5 magrin_top_20">Цены:*</div>

<div class="body-table2">
    <div class="body-table2-cell">
        <div class="body-table2-cell_title">от 35 000 руб</div>
        <div class="body-table2-cell_text">при продвижении<br/>в России</div>
    </div>
    <div class="body-table2-cell">
        <div class="body-table2-cell_title">от 500 у.е</div>
        <div class="body-table2-cell_text">в Беларуси,<br/>других странах СНГ</div>
    </div>
    <div class="body-table2-cell">
        <div class="body-table2-cell_title">от 750 у.е</div>
        <div class="body-table2-cell_text">в Англоязычном сегменте<br/>сети (США, Европа)</div>
    </div>
</div>

<div class="body-block_6 magrin_top_10">
    * Стоимость продвижения формируется на основе целевых ключевых запросов, возраста сайта, уровня конкуренции, и необходимых позиций в поисковых системах.<br/>
    ** Для расчета стоимости, пожалуйста воспользуйтесь формой связи на сайте, позвоните нам или оставьте свой номер - наш менеджер свяжется с вами в ближайшее время.
</div>

<div class="marketing-body-slider">
    <?php echo $this->Marketing(); ?>
</div>

<div class="body-block_7 magrin_top_20">
    <a href="<?= $this->url('page', array('action' => 'checkout')) ?>">
        <div class="body-button">Оформить заказ</div>
    </a>
</div>

<script>
    $(document).ready(function () {
//        var pager,
//                controls,
//                start;
//
//        var pager_controls = function () {
//            if ($(window).width() < 480) {
//                pager = true;
//                controls = false;
//            } else {
//                pager = false;
//                controls = true;
//            }
//        };
//
//        var delay = (function () {
//            var timer = 0;
//            return function (callback, ms) {
//                clearTimeout(timer);
//                timer = setTimeout(callback, ms);
//            };
//        })();
//
//        $(window).resize(function () {
//            delay(function () {
//                pager_controls();
//                start = promotionSlider.getCurrentSlide();
//
//                promotionSlider.destroySlider();
//                promotionSlider.reloadSlider({
//                    slideWidth: $('.promotion .promotion-body-slider').width(),
//                    startSlide: start,
//                    moveSlides: 1,
//                    slideMargin: 0,
//                    controls: controls,
//                    pager: pager,
//                });
//            }, 100);
//        });
//
//        pager_controls();
//        var promotionSlider = $('.promotion .promotion-body-slider').bxSlider({
//            slideWidth: $('.promotion .promotion-body-slider').width(),
//            randomStart: true,
//            moveSlides: 1,
//            slideMargin: 0,
//            controls: controls,
//            pager: pager,
//        });

        var slides = 4;
        var delay = (function () {
            var timer = 0;
            return function (callback, ms) {
                clearTimeout(timer);
                timer = setTimeout(callback, ms);
            };
        })();

        if ($(window).width() < 375) {
            slides = 2;
        } else if ($(window).width() < 510) {
            slides = 3;
        } else {
            slides = 4;
        }

        var slider = $('.marketing-body-slider').bxSlider({
            slideWidth: 105,
            minSlides: 1,
            maxSlides: slides,
            moveSlides: 1,
            slideMargin: 30,
            auto: true,
            pause: 2000,
            controls: false,
            pager: false,
        });

        $(window).resize(function () {
            delay(function () {
                if ($(window).width() < 375) {
                    slides = 2;
                } else if ($(window).width() < 510) {
                    slides = 3;
                } else {
                    slides = 4;
                }
                slider.destroySlider();
                slider.reloadSlider({
                    slideWidth: 105,
                    minSlides: 1,
                    maxSlides: slides,
                    moveSlides: 1,
                    slideMargin: 30,
                    randomStart: true,
                    auto: true,
                    pause: 2000,
                    controls: false,
                    pager: false,
                });
            }, 300);
        });
    });
</script>