<div class="promotion-title-icons">
    <div class="promotion-title-icon publicity_static"></div>
    <div class="promotion-title-icon_main"></div>
    <div class="promotion-title-icon design-static"></div>
</div>
<div class="promotion-title_text">Продвижение</div>

<div class="promotion-body-block_1">
    <p>Это - комплекс мер, направленный на улучшение индексации сайта<br/>
        поисковыми мимтемами и увеличение посещаемости ресурса</p>
</div>

<div class="promotion-body-block_2">
    <p>Азбука вебмедиа™ предлагает вам следущие услуги<br/>
        по раскрутке, продвижению и рекламе в интернете:</p>
</div>

<div class="promotion-body-table">
    <div class="promotion-body-table-cell">
        <div class="promotion-body-table-cell_number">1 </div>
        <div class="promotion-body-table-cell_text">Вывод вашего сайта на вершину поиска</div>
    </div>
    <div class="promotion-body-table-cell">
        <div class="promotion-body-table-cell_number">2 </div>
        <div class="promotion-body-table-cell_text">Внутренняя оптимизация и улучшение юзабилити</div>
    </div>
    <div class="promotion-body-table-cell">
        <div class="promotion-body-table-cell_number">3 </div>
        <div class="promotion-body-table-cell_text">Создание и управление компаниями яндекс.директ и google.adwords</div>
    </div>
    <div class="promotion-body-table-cell">
        <div class="promotion-body-table-cell_number">4 </div>
        <div class="promotion-body-table-cell_text">Внедрение систем мониторинга эффективности рекламы</div>
    </div>
</div>

<div class="promotion-body-block_3">Почему именнно мы?</div>

<ul class="promotion-body-block_4">
    <li>Наша компания более 10 лет занимается продвижением проектов в интернете</li>
    <li>У нас огромный опыт с целевыми рынками США, Европы и России</li>
    <li>Мы используем самые передовые технологии и всегда добиваемся результата</li>
    <li>С нами легко работать. Каждого клиента ведет персональный менеджер</li>
    <li>Мы заботимся о ваших бюджетах и всегда стараемся оптимизировать все процессы для уменьшения расходов</li>
</ul>

<div class="promotion-body-block_5">Мы даем гарантию, что:</div>

<div class="promotion-body-block_6">
    <ul>
        <li>ваши сайты достигнут целевых показателей и надолго закрепяться на первых позициях</li>
        <li>оптимизированные нами страницы продуктов и сайты заметно повысят интерес со стороны посетителей</li>
        <li>сроки выполнения даже самых амбициозных задач не превысят 6 месяцев</li>
    </ul>
</div>

<div class="promotion-body-block_7">Цены:*</div>

<div class="promotion-body-table2">
    <div class="promotion-body-table2-cell">
        <div class="promotion-body-table2-cell_title">от 35 000 руб</div>
        <div class="promotion-body-table2-cell_text">при продвижении<br/>в России</div>
    </div>
    <div class="promotion-body-table2-cell">
        <div class="promotion-body-table2-cell_title">от 500 у.е</div>
        <div class="promotion-body-table2-cell_text">в Беларуси,<br/>других странах СНГ</div>
    </div>
    <div class="promotion-body-table2-cell">
        <div class="promotion-body-table2-cell_title">от 750 у.е.</div>
        <div class="promotion-body-table2-cell_text">в Англоязычном сегменте<br/>сети (США, Европа)</div>
    </div>
</div>

<div class="promotion-body-block_8">* Стоимость продвижения формируется на основе целевых ключевых запросов, возраста сайта, уровня конкуренции, и необходимых позиций в поисковых системах.</div>

<div class="promotion-body-block_8">** Для расчета стоимости, пожалуйста воспользуйтесь формой связи на сайте, позвоните нам или оставьте свой номер - наш менеджер свяжется с вами в ближайшее время.</div>

<div class="promotion-body-carusel">
    <div class="promotion-body-carusel_right"></div>
    <div class="promotion-body-carusel_first"></div>
    <div class="promotion-body-carusel_second"></div>
    <div class="promotion-body-carusel_left"></div>
</div>

<div class="promotion-body-block_9">
    <div class="promotion-body-button_order">ОФОРМИТЬ ЗАКАЗ</div>
    <div class="promotion-body-button_price">РАСЧИТАТЬ ЦЕНУ</div>
    <div class="promotion-body-button_analysis">АНАЛИЗ САЙТА</div>
</div>