<div class="title-icons">
    <a href="<?= $this->url('page', array('action' => 'pr')) ?>">
        <div class="title-icon publicity_static"></div>
    </a>
    <div class="title-icon_main page_promotion"></div>
    <a href="<?= $this->url('page', array('action' => 'design')) ?>">
        <div class="title-icon design_static"></div>
    </a>
</div>
<div class="title_text">Продвижение</div>

<div class="body-block_1  magrin_top_10">
    Это - комплекс мер, направленный на улучшение индексации сайта<br/>
    поисковыми мимтемами и увеличение посещаемости ресурса
</div>

<div class="body-block_2 magrin_top_20">
    Азбука Mediagroup предлагает вам следущие услуги<br/>
    по раскрутке, продвижению и рекламе в интернете:
</div>

<div class="body-table magrin_top_20">
    <div class="body-table-cell">
        <div class="body-table-cell_number">1 </div>
        <div class="body-table-cell_text">Вывод вашего сайта на вершину поиска</div>
    </div>
    <div class="body-table-cell">
        <div class="body-table-cell_number">2 </div>
        <div class="body-table-cell_text">Внутренняя оптимизация и улучшение юзабилити</div>
    </div>
    <div class="body-table-cell">
        <div class="body-table-cell_number">3 </div>
        <div class="body-table-cell_text">Создание и управление компаниями яндекс.директ и google.adwords</div>
    </div>
    <div class="body-table-cell">
        <div class="body-table-cell_number">4 </div>
        <div class="body-table-cell_text">Внедрение систем мониторинга эффективности рекламы</div>
    </div>
</div>

<div class="body-block_3  magrin_top_20">Почему именнно мы?</div>

<ul class="body-ul_1 magrin_top_20">
    <li>Наша компания более 10 лет занимается продвижением проектов в интернете</li>
    <li>У нас огромный опыт с целевыми рынками США, Европы и России</li>
    <li>Мы используем самые передовые технологии и всегда добиваемся результата</li>
    <li>С нами легко работать. Каждого клиента ведет персональный менеджер</li>
    <li>Мы заботимся о ваших бюджетах и всегда стараемся оптимизировать все процессы для уменьшения расходов</li>
</ul>

<div class="body-block_4 magrin_top_20">Мы даем гарантию, что:</div>

<ul class="body-ul_1 body-background magrin_top_10">
    <li>ваши сайты достигнут целевых показателей и надолго закрепяться на первых позициях</li>
    <li>оптимизированные нами страницы продуктов и сайты заметно повысят интерес со стороны посетителей</li>
    <li>сроки выполнения даже самых амбициозных задач не превысят 6 месяцев</li>
</ul>

<div class="body-block_5 magrin_top_10">Цены:*</div>

<div class="body-table2">
    <div class="body-table2-cell">
        <div class="body-table2-cell_title">от 35 000 руб</div>
        <div class="body-table2-cell_text">при продвижении<br/>в России</div>
    </div>
    <div class="body-table2-cell">
        <div class="body-table2-cell_title">от 500 у.е</div>
        <div class="body-table2-cell_text">в Беларуси,<br/>других странах СНГ</div>
    </div>
    <div class="body-table2-cell">
        <div class="body-table2-cell_title">от 750 у.е</div>
        <div class="body-table2-cell_text">в Англоязычном сегменте<br/>сети (США, Европа)</div>
    </div>
</div>

<div class="body-block_6 magrin_top_10">
    * Стоимость продвижения формируется на основе целевых ключевых запросов, возраста сайта, уровня конкуренции, и необходимых позиций в поисковых системах.<br/>
    ** Для расчета стоимости, пожалуйста воспользуйтесь формой связи на сайте, позвоните нам или оставьте свой номер - наш менеджер свяжется с вами в ближайшее время.
</div>

<div class="promotion-body-slider">
    <?php echo $this->Promotion(); ?>
</div>

<div class="body-block_7 magrin_top_20">
    <a href="<?= $this->url('page', array('action' => 'checkout')) ?>">
        <div class="body-button">ОФОРМИТЬ ЗАКАЗ</div>
    </a>
    <div class="body-button">РАСЧИТАТЬ ЦЕНУ</div>
    <div class="body-button">АНАЛИЗ САЙТА</div>
</div>

<script>
    $(document).ready(function () {
        var pager,
                controls,
                start;

        var pager_controls = function () {
            if ($(window).width() < 480) {
                pager = true;
                controls = false;
            } else {
                pager = false;
                controls = true;
            }
        };

        var delay = (function () {
            var timer = 0;
            return function (callback, ms) {
                clearTimeout(timer);
                timer = setTimeout(callback, ms);
            };
        })();

        $(window).resize(function () {
            delay(function () {
                pager_controls();
                start = promotionSlider.getCurrentSlide();

                promotionSlider.destroySlider();
                promotionSlider.reloadSlider({
                    slideWidth: $('.promotion .promotion-body-slider').width(),
                    startSlide: start,
                    moveSlides: 1,
                    slideMargin: 0,
                    controls: controls,
                    pager: pager,
                });
            }, 100);
        });

        pager_controls();
        var promotionSlider = $('.promotion .promotion-body-slider').bxSlider({
            slideWidth: $('.promotion .promotion-body-slider').width(),
            randomStart: true,
            moveSlides: 1,
            slideMargin: 0,
            controls: controls,
            pager: pager,
        });
    });
</script>