<div class="title-contacts"><h1>Пакетные решения</h1></div>

<div class="separator-line">
    <div class="separator"></div>
</div>

<div class="body-block_6 magrin_top_10">
    Мы заботимся о том, чтобы созданные сайты легко находились целевыми
    пользователями в интернете, поэтому мы комплексно подходим к их созданию,
    планируя методы продвижения уже на этапе проектирования    
</div>

<div class="services-table">

    <div class="services-table-content">
        <?php $category = 0; ?> 
        <?php for ($i = 1; $i < 3; $i++) { ?>
            <div class="services-table-title" data-category="<?= $i ?>"><?= $this->services[$category]['category_title'] ?></div>
            <ul class="services-table-content-navigation <?= 'navi_' . $i ?>">
                <?php for ($j = 0; $j < count($this->services); $j++) { ?>
                    <?php if ($i == $this->services[$j]['category']) { ?>
                        <li class="services-table-content-navigation_item" data-id="<?= $this->services[$j]['id']; ?>"><?= $this->services[$j]['title'] ?></li>
                        <?php
                        $category = $j + 1;
                    }
                    ?>
                <?php } ?>
            </ul>
        <?php } ?>
    </div>

    <?php for ($j = 0; $j < count($this->services); $j++) { ?>
        <div class="services-table-content-tabs <?= 'tabs_' . $this->services[$j]['id'] ?>">
            <div class="services-table-column">
                <div class="services-table-column-title">Краткое описание</div>
                <div class="services-table-column-text"><?= $this->services[$j]['description']; ?></div>
                <div class="services-table-column-title">Срок выполнения</div>
                <div class="services-table-column-text"><?= $this->services[$j]['completion_date']; ?></div>
                <div class="services-table-column-title">Отчет</div>
                <div class="services-table-column-text"><?= $this->services[$j]['report']; ?></div>
                <div class="services-table-column-title">Для кого услуга</div>
                <div class="services-table-column-text"><?= $this->services[$j]['services_for']; ?></div>
                <div class="services-table-column-title">Бонус</div>
                <div class="services-table-column-text"><?= $this->services[$j]['bonus']; ?></div>
                <div class="services-table-column-title">Цена</div>
                <div class="services-table-column-text"><?= $this->services[$j]['price']; ?></div>
            </div>
        </div>
    <?php } ?>

</div>

<script>
    $(document).ready(function () {

        var delay = (function () {
            var timer = 0;
            return function (callback, ms) {
                clearTimeout(timer);
                timer = setTimeout(callback, ms);
            };
        })();

//        $(window).resize(function () {        
//            var id = $('.services-table-title-active').data('category');
//            delay(function () {
//                if ($(window).width() >= 800) {
//                    var cool_left = 0;
//                    $('.services-table-title').each(function (index) {
//                        if($(this).data('category') !== id ) {
//                            cool_left += left;
//                            $(this).css('left', cool_left + 'px');
//                        }
//                    });
//                }
//            }, 50);
//        });
// 
        //first show
        $('.navi_2').css('height', '0');
        $('.tabs_' + $('.navi_1').find('.services-table-content-navigation_item').data('id')).show();
        $('.navi_1 .services-table-content-navigation_item:first-of-type').addClass('navigation-active');
        $('.services-table-title:eq(0)').addClass('services-table-title-active');

        $('.services-table-title').on('click', function () {

            var first_div = $('.services-table-title-active'),
                    click_div = $(this),
                    active_category = $('.services-table-title-active').data('category'),
                    click_category = $(this).data('category'),
                    height = $('.navi_' + click_category + ' li').length * 45;

            first_div.removeClass('services-table-title-active');
            click_div.addClass('services-table-title-active');
            $('.navi_' + active_category).animate({height: 0}, "slow");
            $('.navi_' + click_category).animate({height: height}, "slow");
        });

        $('.services-table-content-navigation_item').on('click', function () {
            $('.services-table-content-navigation_item').removeClass('navigation-active');
            $(this).addClass('navigation-active');
            var id = $(this).data('id');
            $('.services-table-content-tabs').stop();
            $('.services-table-content-tabs').hide();
            $('.tabs_' + id).fadeIn(500);
        });
    });
</script>


