<div class="title-line"></div>
<div class="title-contacts"><h1>Сопровождение сайта</h1></div>
<div class="title-line"></div>

<div class="promotion-body-block_1">
    Мы заботимся о том, чтобы созданные нами сайты легко находились целевыми
    пользователями в интернете, поэтому мы комплексно подходим у их созданию
    , планируя методы продвижения уже на этапе проектирования
</div>

<div class="promotion-body-block_9">
    <a href="<?= $this->url('page', array('action' => 'checkout')) ?>">
        <div class="promotion-body-button_order">ОФОРМИТЬ ЗАКАЗ</div>
    </a>
</div>

<style>
    body.support .title-line {
        width: 175px;
    }
    
    body.support .title-contacts {
        width: 440px;
    }
</style>