<div class="portfolio-body-slider">
    <?php echo $this->Portfolio(); ?>
</div>

<div class="body-block_7">
    <a href="<?= $this->url('admin', array('action' => 'addportfolio')) ?>">
        <div class="body-button">Создать новое</div>
    </a>
    <div class="body-button delete">Удалить</div>
    <div class="body-button edit">Редактировать</div>
    <a href="<?= $this->url('admin', array('action' => 'index')) ?>">
        <div class="body-button">Назад</div>
    </a>
</div>

<script>
    $(document).ready(function () {
        var width = 720;

        if ($('.content').width() < 800 || screen.width < 800) {
            width = 320;
        } else {
            width = 720;
        }


        $('.portfolio-body-slider-item_left').bxSlider({
            slideWidth: 365,
            mode: 'vertical',
            moveSlides: 1,
            slideMargin: 0,
            controls: false,
            pager: true,
        });

        var portfolioSlider = $('.portfolio-body-slider').bxSlider({
            slideWidth: width,
            moveSlides: 1,
            slideMargin: 0,
            controls: true,
            pager: false,
        });
        
        $('.edit').on('click', function () {
            var current = portfolioSlider.getCurrentSlide() + 1,
                    id;
                    
            $('.portfolio-body-slider').children().each(function (index) {
                if (current == index) {
                    id = $(this).data('id');
                }
            });
            
            document.location.href = "/admin/addportfolio/" + id;
        });

        $('.delete').on('click', function () {
            var current = portfolioSlider.getCurrentSlide() + 1,
                    id,
                    item;
                    
            $('.portfolio-body-slider').children().each(function (index) {
                if (current == index) {
                    id = $(this).data('id');
                    item = $(this);
                }
            });

            if (id) {
                $.ajax({
                    type: "POST",
                    url: "/admin/deletePortfolio",
                    data: {"id": id},
                    cache: false,
                    success: function (response) {
                        if (response && response.status === 'ok') {
                            item.remove();
                        }
                    }
                });
            }

        });
    });
</script>

