<?php echo $this->doctype(); ?>

<html lang="ru">
    <head>
        <meta charset="utf-8">
        <?php $meta = $this->MetaHelper() ?>

        <?php echo $this->headTitle($meta['title']) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, height=device-height, initial-scale=1.0')
                ->appendName('keywords', $meta['keywords'])
                ->appendName('description', $meta['description'])// и это и кеуворды
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.jpg'))
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/uikit.docs.min.css')
                ->prependStylesheet($this->basePath() . '/css/jquery.bxslider.css')
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/js/dropzone.js')
                ->prependFile($this->basePath() . '/js/jquery.autosize.min.js')
                ->prependFile($this->basePath() . '/js/jquery.bxslider.min.js')
                ->prependFile($this->basePath() . '/js/uikit.min.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js')
                ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ;
        ?>

    </head>
    <body class="<?= $this->controllerName()['controller'] . ' ' . $this->controllerName()['action']; ?>">
        <div id="preloader">
            <div id="status">&nbsp;</div>
        </div>
        <div class="wrapper">
            <nav> 
                <div id="navigation-active-logo"></div>
                <div class="nav-left">
                    <a class="main-logo" href="/">
                    </a>
                </div>
                <div class="nav-right">
                    <a href="#" class="nav-right-language">EN</a>
                    <a href="#" class="nav-right-language active-language">RU</a>
                </div>
                <?= $this->navigation('Navigation')->menu()->renderMenu(null, array('renderParents' => true)); ?>
                <div class="menu-line"></div>
                <div id="nav-menu-icon"></div>
            </nav>

            <div class="container">
                <?php if ($meta['form']) { ?>
                    <?php
                    $form = $meta['form'];
                    $form->prepare();
                    $form->setAttribute('action', $this->url('admin', array('action' => 'saveHeadmeta')));
                    ;
                    echo $this->form()->openTag($form);
                    ?>


                    <div class="headmeta feedback-form-content">
                        <?= $this->formLabel($form->get('controller')); ?>
                        <div class="form-input"><?= $this->formElement($form->get('controller')); ?></div>

                        <?= $this->formLabel($form->get('action')); ?>
                        <div class="form-input user-data"><?= $this->formElement($form->get('action')); ?></div>

                        <?= $this->formLabel($form->get('title')); ?>
                        <div class="form-input user-data"><?= $this->formElement($form->get('title')); ?></div>

                        <?= $this->formLabel($form->get('description')); ?>
                        <div class="form-input"><?= $this->formElement($form->get('description')); ?></div>

                        <?= $this->formLabel($form->get('keywords')); ?>
                        <div class="form-input"><?= $this->formElement($form->get('keywords')); ?></div>

                        <div class="form-submit"><?= $this->formElement($form->get('submit')); ?></div>	

                    </div>
                    <?php echo $this->form()->closeTag(); ?>
                <?php } ?>

                <div class="content">
                    <?php echo $this->content; ?>
                </div>
            </div>  
        </div>
        <a href="<?= $this->url('page', array('action' => 'contacts')) ?>">
            <button class="contacts-button">Связаться с нами</button>
        </a>
        <footer>
            <div class="footer-social-icons">
                <a class="social-icon twitter" href="#"></a>
                <a class="social-icon facebook" href="#"></a>
                <a class="social-icon google" href="#"></a>
                <a class="social-icon vk" href="#"></a>
            </div>
            <div class="footer-bottom">
                <?= $this->navigation('Navigation')->menu()->renderMenu(null, array('renderParents' => true)); ?>
            </div>
        </footer>


        <script type="text/javascript">
            $(document).ready(function () {
                var li_offset,
                        li_width,
                        nav_div = $('#navigation-active-logo'),
                        flag,
                        li = $('nav .navigation > li.active');

                var delay = (function () {
                    var timer = 0;
                    return function (callback, ms) {
                        clearTimeout(timer);
                        timer = setTimeout(callback, ms);
                    };
                })();  

                //MENU
                delay(function () {
                    active_li();
                }, 200);
                
                $(window).resize(function () {
                    active_li();
                });
                
                var active_li = function () {
                    if ($(window).width() > 983) {
                        li = $('nav .navigation > li.active');
                        li_width = li.width();
                        li_offset = li.offset().left;
                        nav_div.offset({left: li_offset + li_width / 2 - 15});
                        nav_div.show();
                        $('nav .navigation ul').hide();
                        li = $('nav .navigation > li.active ul').fadeIn();
                    } else {
                        nav_div.offset({left: 0});
                        nav_div.hide();
                        $('nav .navigation ul').fadeIn();
                    }
                };
                
                flag = true;
                $('nav .navigation > li > a').hover(function () {
                    
                    if (flag && (li.width() !== $(this).parent().width())) {
                        flag = false;
                        li = $(this).parent();

                        li_offset = li.offset().left;
                        li_width = li.width();
                        nav_div.show();
                        nav_div.animate({left: li_offset + li_width / 2 - 15}, {duration: 500,
                            specialEasing: {
                                width: "linear",
                                height: "easeOutBounce"
                            },
                            progress: function () {
                                $('nav .navigation ul').fadeOut();
                            },
                            start: function () {
                                delay(function () {
                                    flag = true;
                                }, 200);
                            },
                            complete: function () {
                                li.children('ul').fadeIn();
                            }
                        });
                    }
                });
                //END MENU

                var height;
                $('#nav-menu-icon').on('click', function () {
                    height = $('nav .navigation > li:last-of-type').offset().top - 50;
                    if (!$('nav .navigation').height()) {
                        $('nav .navigation').stop().animate({height: height}, "slow");
                    } else if (height === $('nav .navigation').height()) {
                        $('nav .navigation').stop().animate({height: 0}, "slow");
                    }
                });
                $('textarea').autosize();
            });
        </script>
    </body>
</html>
