<?php echo $this->doctype(); ?>

<html lang="ru">
    <head>
        <meta charset="utf-8">
        <?php $meta = $this->MetaHelper() ?>

        <?php echo $this->headTitle($meta['title']) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, height=device-height, initial-scale=1.0')
                ->appendName('keywords', $meta['keywords'])
                ->appendName('description', $meta['description'])// и это и кеуворды
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.jpg'))
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/jquery.bxslider.css')
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/js/dropzone.js')
                ->prependFile($this->basePath() . '/js/jquery.autosize.min.js')
                ->prependFile($this->basePath() . '/js/jquery.bxslider.min.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js')
                ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ;
        ?>

    </head>
    <body class="<?= $this->controllerName()['controller'] . ' ' . $this->controllerName()['action']; ?>">
        <div class="wrapper">
            <nav> 
                <div class="menu"></div>
                <div class="nav-left">
                    <a class="main-logo" href="/">
                    </a>
                </div>
                <div class="nav-right">
                    <div class="icon-phone"></div>
                    <div class="phones">
                        <div class="phone-skype">
                            <a class="skype-call-number" href="#">+375 29 615-27-93</a>
                        </div>
                        <div class="phone-skype">
                            <a class="skype-call-number" href="#">+375 33 615-27-93</a>
                        </div>
                    </div>
                </div>
            </nav>
            <div class="wrap-menu">
                <div class="wrap-menu-items">
                    <div class="menu-item">
                        <h2>
                            <a href="<?= $this->url('page', array('action' => 'promotion')) ?>">Продвижение</a>
                        </h2>
                        <br/>
                        <div class="menu-item_links">
                            <p><a href="#">Привлечение целевых клиентов</a></p>
                            <p><a href="#">Старт быстрых продаж</a></p>
                            <p><a href="#">Юзабилити-аудит сайта</a></p>
                        </div>
                    </div>
                    <div class="menu-item">
                        <h2>
                            <a href="<?= $this->url('page', array('action' => 'design')) ?>">WEB Design</a>
                        </h2>
                        <br/>
                        <div class="menu-item_links">
                            <p><a href="<?= $this->url('page', array('action' => 'portfolio')) ?>">Портфолио</a></p>
                        </div>
                    </div>
                    <div class="menu-item">
                        <h2>
                            <a href="<?= $this->url('page', array('action' => 'marketing')) ?>">WEB Маркетинг</a>
                        </h2>
                        <br/>
                        <div class="menu-item_links">
                            <p><a href="#">Исследование покупательской<br/>способности</a></p>
                            <p><a href="#">Маркетинговые исследования</a></p>
                            <p><a href="#">Страницы товаров</a></p>
                        </div>
                    </div>
                    <div class="menu-item">
                        <h2>
                            <a href="<?= $this->url('page', array('action' => 'pr')) ?>">Реклама и PR</a>
                        </h2>
                        <br/>
                        <div class="menu-item_links">
                            <p><a href="#">Привлечение аудитории</a></p>
                            <p><a href="#">Баннерная реклама</a></p>
                            <p><a href="<?= $this->url('page', array('action' => 'brend')) ?>">Узнаваемость бренда</a></p>
                        </div>
                    </div>
                    <div class="menu-item">
                        <h2>
                            <a href="<?= $this->url('page', array('action' => 'contacts')) ?>">Контакты</a>
                        </h2>
                        <br/>
                        <div class="menu-item_links">
                        </div>
                    </div>
                </div>
            </div>
            <div class="container">
                <?php if ($meta['form']) { ?>
                    <?php
                    $form = $meta['form'];
                    $form->prepare();
                    $form->setAttribute('action', $this->url('admin', array('action' => 'saveHeadmeta')));;
                    echo $this->form()->openTag($form);
                    ?>


                    <div class="headmeta feedback-form-content">
                        <?= $this->formLabel($form->get('controller')); ?>
                        <div class="form-input"><?= $this->formElement($form->get('controller')); ?></div>
                        
                        <?= $this->formLabel($form->get('action')); ?>
                        <div class="form-input user-data"><?= $this->formElement($form->get('action')); ?></div>

                        <?= $this->formLabel($form->get('title')); ?>
                        <div class="form-input user-data"><?= $this->formElement($form->get('title')); ?></div>

                        <?= $this->formLabel($form->get('description')); ?>
                        <div class="form-input"><?= $this->formElement($form->get('description')); ?></div>
                        
                        <?= $this->formLabel($form->get('keywords')); ?>
                        <div class="form-input"><?= $this->formElement($form->get('keywords')); ?></div>

                        <div class="form-submit"><?= $this->formElement($form->get('submit')); ?></div>	

                    </div>
                    <?php echo $this->form()->closeTag(); ?>
                <?php } ?>

                <div class="content">
                    <?php echo $this->content; ?>
                </div>
            </div>  
        </div>
        <a href="<?= $this->url('page', array('action' => 'contacts')) ?>">
            <button class="contacts-button">Связаться с нами</button>
        </a>
        <footer>
            <div class="footer-social-icons">
                <a class="social-icon twitter" href="#"></a>
                <a class="social-icon facebook" href="#"></a>
                <a class="social-icon google" href="#"></a>
                <a class="social-icon vk" href="#"></a>
            </div>
        </footer>


        <script type="text/javascript">
            $(document).ready(function () {
                var speed = 1000,
                        originalHeight = 0,
                        hoverHeight;

                $('.menu').on('click', function () {
                    hoverHeight = $('.wrap-menu-items').height();
                    if (parseInt($('.wrap-menu').height()) == originalHeight) {
                        $('.wrap-menu').animate({height: hoverHeight}, speed);
                        $('.menu').css('background-image', 'url(img/menu_active.png)');
                    } else {
                        $('.wrap-menu').animate({height: originalHeight}, speed);
                        $('.menu').css('background-image', 'url(img/menu.png)');
                    }
                });

                $('textarea').autosize();
                
                $('.form-submit').on('click', function() {
                    
                });

            });
        </script>
    </body>
</html>
