<div class="slider">
    <div class="slider-big-text">Приветствуем вас на нашем сайте</div>
    <div class="slider-small-text">Hello friend's</div>
</div>

<div class="main-navigation">
    <div class="main-navigation-item">
        <a href="<?= $this->url('page', array('action' => 'promotion')) ?>">
            <img class="main-navigation-item_image promotion right-align" alt="Продвижение в поисковых системах" src="/img/promotion.png">
            <div class="caption right-align">
                <h3>Продвижение</h3>
                <p>В поисковых<br/> системах</p>
            </div>     
        </a>
    </div>
    <div class="main-navigation-item">
        <a href="<?= $this->url('page', array('action' => 'design')) ?>">
            <img class="main-navigation-item_image design right-align" alt="WEB Design" src="/img/design.png">
            <div class="caption right-align">
                <h3>WEB Design</h3>
                <p>Создание<br/> сайтов</p>
            </div>     
        </a>
    </div>
    <div class="main-navigation-item">
        <a href="<?= $this->url('page', array('action' => 'marketing')) ?>">
            <img class="main-navigation-item_image marketing left-align" alt="WEB маркетинг" src="/img/marketing.png">
            <div class="caption left-align">
                <h3>WEB маркетинг</h3>
                <p>и управлние <br/> репутацией</p>
            </div>     
        </a>
    </div>
    <div class="main-navigation-item">
        <a href="<?= $this->url('page', array('action' => 'publicity')) ?>">
            <img class="main-navigation-item_image publicity left-align" alt="Реклама" src="/img/publicity.png">
            <div class="caption left-align">
                <h3>Реклама и PR</h3>
                <p>В социальных <br/> сетях</p>
            </div>     
        </a>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        var src;
        $(".main-navigation-item").on({
            mouseenter: function () {
                src = $(this).find('.main-navigation-item_image').attr('src');
                $(this).find('.main-navigation-item_image').attr('src', src.substring(0, src.length - 4) + '_hover.png');
            },
            mouseleave: function () {
                $(this).find('.main-navigation-item_image').attr('src', src);
            }
        });
    });
</script>