<div class="slider">
    <div class="slider-item">
        <div class="slider-big-text">Желаете быть первыми в поисковых системах Яндекс и Google?</div>
    </div>
    <div class="slider-item">
        <div class="slider-big-text">Продвижение сайтов в России, Беларуси, Европе и США.</div>
        <div class="slider-small-text">Мы - мастера своего дела: 14 лет работы. Более 2000 успешных проектов.</div>
        <div class="slider-small-text">Закажите рекламу Яндекс.директ или Google.adwords и вы получите новых клиентов уже на следующий день!</div>
    </div>
    <div class="slider-item">
        <div class="slider-big-text">Мы создаем красивые и удобные сайты в которые вложена частичка души.</div>
        <div class="slider-small-text">Интернет магазины которые продают.</div>
        <div class="slider-small-text">Разработка НЕОБЫКНОВЕННЫХ сайтов для частных компаний.</div>
        <div class="slider-small-text">Сайты которыми УДОБНО пользоваться с телефона.</div>
    </div>
    <div class="slider-item">
        <div class="slider-big-text">Интернет - глобальный рынок всего.</div>
        <div class="slider-small-text">Информация - основа принятия решений.</div>
    </div>
    <div class="slider-item">
        <div class="slider-big-text">Забота о вашей репутации в интернете.</div>
        <div class="slider-small-text">Маркетинговые исследования. От запуска пробных продуктов до комплексного анализа рынка.</div>
        <div class="slider-small-text">Создание и популяризация вашего бренда.</div>
    </div>
    <div class="slider-item">
        <div class="slider-big-text">Социальные сети</div>
        <div class="slider-small-text">Создание и оформление страниц в социальных сетях</div>
        <div class="slider-small-text">Привлечение посетителей из социальных сетей</div>
        <div class="slider-small-text">Вирусная реклама</div>
    </div>
</div>

<div class="main-navigation">
    <div class="main-navigation-item">
        <a href="<?= $this->url('page', array('action' => 'promotion')) ?>">
            <img class="main-navigation-item_image promotion right-align" alt="Продвижение в поисковых системах" src="/img/promotion_hover.png">
            <div class="caption right-align">
                <h3>Продвижение</h3>
                <p>В поисковых<br/> системах</p>
            </div>     
        </a>
    </div>
    <div class="main-navigation-item">
        <a href="<?= $this->url('page', array('action' => 'design')) ?>">
            <img class="main-navigation-item_image design right-align" alt="WEB Design" src="/img/design_hover.png">
            <div class="caption right-align">
                <h3>WEB Design</h3>
                <p>Создание<br/> сайтов</p>
            </div>     
        </a>
    </div>
    <div class="main-navigation-item">
        <a href="<?= $this->url('page', array('action' => 'marketing')) ?>">
            <img class="main-navigation-item_image marketing left-align" alt="WEB маркетинг" src="/img/marketing_hover.png">
            <div class="caption left-align">
                <h3>WEB маркетинг</h3>
                <p>и управлние <br/> репутацией</p>
            </div>     
        </a>
    </div>
    <div class="main-navigation-item">
        <a href="<?= $this->url('page', array('action' => 'pr')) ?>">
            <img class="main-navigation-item_image publicity left-align" alt="Реклама" src="/img/pr_hover.png">
            <div class="caption left-align">
                <h3>Реклама и PR</h3>
                <p>В социальных <br/> сетях</p>
            </div>     
        </a>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        var src;
        $(".main-navigation-item").on({
            mouseenter: function () {
                src = $(this).find('.main-navigation-item_image').attr('src');
                $(this).find('.main-navigation-item_image').attr('src', src.substring(0, src.length - 10) + '.png');
            },
            mouseleave: function () {
                $(this).find('.main-navigation-item_image').attr('src', src);
            }
        });

        var slider = $('.slider').bxSlider({
            minSlides: 1,
            moveSlides: 1,
            auto: true,
            pause: 3000,
            controls: false,
            pager: true,
        });

        $('.slider').on({
            mouseenter: function () {
                slider.stopAuto();
            },
            mouseleave: function () {
                slider.startAuto();
            }
        });

    });
</script>